# Generated by Django 3.1.4 on 2022-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220203_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories/'),
        ),
    ]
