# Generated by Django 3.1.4 on 2022-04-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_subcategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
