# Generated by Django 3.1.4 on 2022-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='specifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcategories', to='mainapp.Specification'),
        ),
    ]
