# Generated by Django 4.0.3 on 2022-04-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_productspecifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpecifications',
            new_name='ProductSpecification',
        ),
    ]
