# Generated by Django 4.0.3 on 2022-04-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_subcategoryspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='subcategoryspecification',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryspecifications', to='mainapp.specification'),
        ),
        migrations.AlterField(
            model_name='subcategoryspecification',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryspecifications', to='mainapp.subcategory'),
        ),
    ]
