# Generated by Django 4.0.3 on 2022-04-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_subcategory_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='specification',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='subcategoryspecification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productspecifications', to='mainapp.subcategoryspecification'),
        ),
    ]
