# Generated by Django 3.1.4 on 2022-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstblock_img', models.ImageField(blank=True, null=True, upload_to='indexpage/')),
                ('firstblock_title', models.CharField(blank=True, max_length=200, null=True)),
                ('firstblock_sec_title', models.CharField(blank=True, max_length=200, null=True)),
                ('firstblock_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
