# Generated by Django 3.1.4 on 2022-02-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_indexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpage',
            old_name='firstblock_sec_title',
            new_name='firstblock_subtitle',
        ),
    ]
