# Generated by Django 3.1.4 on 2022-02-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20220205_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_first_first_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_first_img',
            field=models.ImageField(blank=True, null=True, upload_to='indexpage/'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_first_second_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_first_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_second_first_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_second_img',
            field=models.ImageField(blank=True, null=True, upload_to='indexpage/'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_second_second_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_second_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_third_first_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_third_img',
            field=models.ImageField(blank=True, null=True, upload_to='indexpage/'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_third_second_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_third_subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
