# Generated by Django 3.1.4 on 2022-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_first_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_second_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='secondblock_third_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
